### PR TITLE
support Jupyter notebook + add ipynb article

### PR DESCRIPTION
**Pull request by mgu**
This PR add a submodule to the repository, tell me if you can't deal with it

screenshot-localhost 8000-2018-03-01-12-01-48

### CODE REVIEW

**Comment by xcambar** [comment]
ping @rodo @SdgJlbl

**Comment by mgu** [comment]
I don't know what is the process on this repository.
Who should merge and deploy ? when ?

**Comment by rodo** [comment]
We may follow a KISS process, 2 reviewers, and with no objection the 2nd who is agree merge. And be in charge of finding someone who can publish (I'm one of the by the way)

**Comment by rodo** [comment]
Je merge, il faut que l'on soit tous aussi un peu réactif, sinon on risque de démotiver les gens qui écrivent des articles

**Pull request merged**
