### PR TITLE
Fix nitpicks https

### PR DESCRIPTION
**Pull request by wo0dyn**
## ChangeLog

* Use Google Fonts with https
* Add PeopleDoc UI's fonts

### CODE REVIEW

**Comment by wo0dyn** [comment]
Don't merge now please. I need to check something else.

**Comment by wo0dyn** [comment]
@xcambar, does it look good to you?

**Comment by wo0dyn** [comment]
<table>
<tr>
<th align=center>Before
<th align=center>After
<tr>
<td align=center>
<br>

screenshot 2018-03-07 at 22 40 30

<td align=center>
<br>

screenshot 2018-03-07 at 22 40 42

</table>

Well, OK, that was probably a nice suggestion @xcambar. :grin:

**Comment by rodo** [comment]
Published !

**Comment by wo0dyn** [comment]
Thanks @rodo.

**Pull request merged**
